# Generated by Django 4.2.1 on 2023-11-06 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_macky', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='included_in_gallery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formattribute',
            name='display_in_gallery',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='record',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recordcomment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='app_macky.form')),
            ],
            options={
                'unique_together': {('form', 'created_at')},
            },
        ),
    ]
