# Generated by Django 4.2.1 on 2023-11-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_macky', '0003_remove_formattribute_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='gallery_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
