# Generated by Django 4.2.1 on 2023-11-12 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_macky', '0004_gallery_gallery_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formattribute',
            name='record',
        ),
        migrations.RemoveField(
            model_name='formattribute',
            name='value',
        ),
        migrations.CreateModel(
            name='FormAttributeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('form_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_macky.formattribute')),
                ('record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_macky.record')),
            ],
        ),
    ]
