# Generated by Django 4.2.1 on 2023-11-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_macky', '0006_attribute_updated_at_formattribute_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formattribute',
            name='display_in_gallery',
            field=models.BooleanField(default=False),
        ),
    ]
