# Generated by Django 4.2.1 on 2023-11-22 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_macky', '0007_alter_formattribute_display_in_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='thumb_down',
        ),
        migrations.RemoveField(
            model_name='record',
            name='thumb_up',
        ),
    ]
