# Generated by Django 4.2.1 on 2023-11-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_macky', '0008_remove_record_thumb_down_remove_record_thumb_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='recordcomment',
            name='aproved_by_admin',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='recordcomment',
            name='comment',
            field=models.TextField(default=''),
        ),
    ]
