# Generated by Django 4.2.1 on 2024-05-03 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_macky', '0011_remove_attribute_required_formattribute_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_macky.form'),
        ),
    ]
