# Generated by Django 4.2.1 on 2024-05-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_macky', '0012_record_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formattribute',
            name='display_in_gallery',
            field=models.BooleanField(default=True),
        ),
    ]
