# Generated by Django 4.2.1 on 2024-05-13 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_macky', '0013_alter_formattribute_display_in_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atribut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vytvoreny', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('aktualizovany', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Formular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vytvoreny', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('aktualizovany', models.DateTimeField(default=django.utils.timezone.now)),
                ('formular_nazov', models.CharField(max_length=255)),
                ('zobrazit_v_galerii', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormularAtribut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vytvoreny', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('aktualizovany', models.DateTimeField(default=django.utils.timezone.now)),
                ('povinny', models.BooleanField(default=True)),
                ('zobrazit_v_galerii', models.BooleanField(default=True)),
                ('atribut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_macky.atribut')),
                ('formular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_macky.formular')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormularAtributUdaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vytvoreny', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('aktualizovany', models.DateTimeField(default=django.utils.timezone.now)),
                ('hodnota', models.CharField(blank=True, max_length=512, null=True)),
                ('formular_atribut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_macky.formularatribut')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vytvoreny', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('aktualizovany', models.DateTimeField(default=django.utils.timezone.now)),
                ('nazov', models.CharField(default='', max_length=255)),
                ('formular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='app_macky.formular')),
            ],
            options={
                'unique_together': {('formular', 'vytvoreny')},
            },
        ),
        migrations.CreateModel(
            name='Hlas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vytvoreny', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('aktualizovany', models.DateTimeField(default=django.utils.timezone.now)),
                ('typ_hlasu', models.CharField(choices=[('up', 'Upvote'), ('down', 'Downvote')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Zaznam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vytvoreny', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('aktualizovany', models.DateTimeField(default=django.utils.timezone.now)),
                ('opis', models.TextField(default='')),
                ('formular', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_macky.formular')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ZaznamKomentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vytvoreny', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('aktualizovany', models.DateTimeField(default=django.utils.timezone.now)),
                ('komentar', models.TextField(default='')),
                ('povoleny_adminom', models.BooleanField(default=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('zaznam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_macky.zaznam')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='formattribute',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='formattribute',
            name='form',
        ),
        migrations.RemoveField(
            model_name='formattributedata',
            name='form_attribute',
        ),
        migrations.RemoveField(
            model_name='formattributedata',
            name='record',
        ),
        migrations.AlterUniqueTogether(
            name='gallery',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='form',
        ),
        migrations.RemoveField(
            model_name='record',
            name='form',
        ),
        migrations.RemoveField(
            model_name='record',
            name='user',
        ),
        migrations.RemoveField(
            model_name='recordcomment',
            name='record',
        ),
        migrations.RemoveField(
            model_name='recordcomment',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='vote',
            name='record',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='user',
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
        migrations.DeleteModel(
            name='Form',
        ),
        migrations.DeleteModel(
            name='FormAttribute',
        ),
        migrations.DeleteModel(
            name='FormAttributeData',
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.DeleteModel(
            name='Record',
        ),
        migrations.DeleteModel(
            name='RecordComment',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
        migrations.AddField(
            model_name='hlas',
            name='zaznam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_macky.zaznam'),
        ),
        migrations.AddField(
            model_name='formularatributudaje',
            name='record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_macky.zaznam'),
        ),
        migrations.AlterUniqueTogether(
            name='hlas',
            unique_together={('user', 'zaznam')},
        ),
    ]
