# Generated by Django 4.2.1 on 2024-05-13 15:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_macky', '0014_atribut_formular_formularatribut_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormularAtribut',
            new_name='Formular_Atribut',
        ),
        migrations.RenameModel(
            old_name='FormularAtributUdaje',
            new_name='Formular_Atribut_Udaje',
        ),
        migrations.RenameModel(
            old_name='ZaznamKomentar',
            new_name='Zaznam_Komentar',
        ),
    ]
