# Generated by Django 4.2.1 on 2024-05-13 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_macky', '0015_rename_formularatribut_formular_atribut_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atribut',
            old_name='name',
            new_name='nazov',
        ),
        migrations.RenameField(
            model_name='atribut',
            old_name='type',
            new_name='typ',
        ),
        migrations.RenameField(
            model_name='galeria',
            old_name='nazov',
            new_name='galeria_nazov',
        ),
    ]
