# Generated by Django 4.2.1 on 2024-05-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_macky', '0017_rename_record_formular_atribut_udaje_zaznam'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='zaznam',
            index=models.Index(fields=['user'], name='app_macky_z_user_id_124fe6_idx'),
        ),
    ]
