# Generated by Django 4.2.1 on 2024-05-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_macky', '0018_zaznam_app_macky_z_user_id_124fe6_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='formular_atribut',
            index=models.Index(fields=['formular'], name='app_macky_f_formula_1adf02_idx'),
        ),
        migrations.AddIndex(
            model_name='formular_atribut_udaje',
            index=models.Index(fields=['zaznam'], name='app_macky_f_zaznam__21c426_idx'),
        ),
        migrations.AddIndex(
            model_name='hlas',
            index=models.Index(fields=['zaznam'], name='app_macky_h_zaznam__9f0580_idx'),
        ),
        migrations.AddIndex(
            model_name='zaznam_komentar',
            index=models.Index(fields=['zaznam'], name='app_macky_z_zaznam__b0c22e_idx'),
        ),
    ]
