# Generated by Django 4.2.1 on 2024-05-20 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_macky', '0019_formular_atribut_app_macky_f_formula_1adf02_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='zaznam',
            new_name='zaznam_user_id_659a03_idx',
            old_name='app_macky_z_user_id_124fe6_idx',
        ),
        migrations.AlterModelTable(
            name='zaznam',
            table='zaznam',
        ),
    ]
