# Generated by Django 4.2.1 on 2024-05-20 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_macky', '0020_rename_app_macky_z_user_id_124fe6_idx_zaznam_user_id_659a03_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='formular_atribut',
            new_name='formular_at_formula_aaeaac_idx',
            old_name='app_macky_f_formula_1adf02_idx',
        ),
        migrations.RenameIndex(
            model_name='formular_atribut_udaje',
            new_name='formular_at_zaznam__13fd92_idx',
            old_name='app_macky_f_zaznam__21c426_idx',
        ),
        migrations.RenameIndex(
            model_name='hlas',
            new_name='hlas_zaznam__6f865e_idx',
            old_name='app_macky_h_zaznam__9f0580_idx',
        ),
        migrations.RenameIndex(
            model_name='zaznam_komentar',
            new_name='zaznam_kome_zaznam__ad11de_idx',
            old_name='app_macky_z_zaznam__b0c22e_idx',
        ),
        migrations.AlterModelTable(
            name='atribut',
            table='atribut',
        ),
        migrations.AlterModelTable(
            name='formular',
            table='formular',
        ),
        migrations.AlterModelTable(
            name='formular_atribut',
            table='formular_atribut',
        ),
        migrations.AlterModelTable(
            name='formular_atribut_udaje',
            table='formular_atribut_udaje',
        ),
        migrations.AlterModelTable(
            name='galeria',
            table='galeria',
        ),
        migrations.AlterModelTable(
            name='hlas',
            table='hlas',
        ),
        migrations.AlterModelTable(
            name='zaznam_komentar',
            table='zaznam_komentar',
        ),
    ]
